version: '3.9'

services:
  web:
    build:
      dockerfile: Dockerfile
    command: streamlit run Dashboard.py
    volumes:
      - ./project:/povtrait-app
    ports:
      - 8501:8501
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    depends_on:
      - db



