version: '3.9'

services:
  web:
    build:
      dockerfile: Dockerfile
    command: streamlit run Dashboard.py --workers 1 --host 0.0.0.0 --port 8501
    volumes:
      - ./project:/povtrait-app
    ports:
      - 8501:8501
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    depends_on:
      - db



